/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Coordinador.CoordinadorPantallas;
import Persistencia.MesaDAO;
import Pojos.Mesa;
import exception.PersistenciaException;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduar
 */
public class AdministrarMesas extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarMesas
     */
    public AdministrarMesas() {
        initComponents();
        cargarTabla();
        
        // Agregamos el evento para que al hacer clic en una fila, se actualicen los campos de texto
    tblMesas.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int filaSeleccionada = tblMesas.getSelectedRow();
            if (filaSeleccionada != -1) {
                // Extraer el número de mesa y la capacidad desde la fila seleccionada
                numeroMesa.setText(tblMesas.getValueAt(filaSeleccionada, 3).toString());
                CapacidadMesa.setText(tblMesas.getValueAt(filaSeleccionada, 1).toString());
            }
        }
    });
        
    }

     private void cargarTabla() {
    try {
        MesaDAO mesaDao = MesaDAO.getInstanceDAO(); // Obtener instancia del DAO
        List<Mesa> mesa = mesaDao.obtenerTodasLasMesas(); // Obtener reservaciones desde JPA
        
        DefaultTableModel modelo = (DefaultTableModel) tblMesas.getModel();
        modelo.setRowCount(0); // Limpiar tabla antes de agregar datos

        for (Mesa m : mesa) {
            modelo.addRow(new Object[]{
               
                m.getCapacidadMesa(),
                m.isDisponible(),
                m.getNumeroMesa(),
                m.getEstadoMesa()
            });
        }
    } catch (PersistenciaException e) {
        e.printStackTrace(); // Manejo de errores
    }
}
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEnServicio = new javax.swing.JButton();
        btnDisponible = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CapacidadMesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numeroMesa = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnCambiarCapacidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Capacidad", "Disponible", "Numero de Mesa", "Estado de Mesa"
            }
        ));
        jScrollPane1.setViewportView(tblMesas);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion de Mesas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnEnServicio.setText("En servicio");
        btnEnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnServicioActionPerformed(evt);
            }
        });

        btnDisponible.setText("Disponible");
        btnDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponibleActionPerformed(evt);
            }
        });

        jLabel2.setText("Capaciad");

        CapacidadMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadMesaActionPerformed(evt);
            }
        });

        jLabel3.setText("Mesa ");

        numeroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroMesaActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnCambiarCapacidad.setText("Cambiar Capacidad");
        btnCambiarCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCapacidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCambiarCapacidad)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEnServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(numeroMesa)
                                .addComponent(CapacidadMesa)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CapacidadMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnServicioActionPerformed
        // Verificar que se haya seleccionado una fila en la tabla
    int filaSeleccionada = tblMesas.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa en la tabla.");
        return;
    }
    
    // Sacamos el número de mesa, asumiendo que está en la columna 3.
    int numMesa = Integer.parseInt(tblMesas.getValueAt(filaSeleccionada, 3).toString());
    
    // Actualizamos el estadoMesa a 2 ("En servicio") usando una consulta JPQL directamente
   /* EntityManager em = conexion.Conexion.crearConexion();
    try {
        em.getTransaction().begin();
        int updated = em.createQuery("UPDATE Mesa m SET m.EstadoMesa = :nuevoEstado WHERE m.numeroMesa = :numMesa")
                        .setParameter("nuevoEstado", 2)
                        .setParameter("numMesa", numMesa)
                        .executeUpdate();
        em.getTransaction().commit();
        
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "La mesa " + numMesa + " se ha marcado como 'En servicio'.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la mesa con número: " + numMesa);
        }
        cargarTabla();  // Recargar la tabla para ver el cambio.
    } catch (Exception e) {
        if (em.getTransaction().isActive()) {
            em.getTransaction().rollback();
        }
        JOptionPane.showMessageDialog(this, "Error al actualizar la mesa: " + e.getMessage());
        e.printStackTrace();
    } finally {
        em.close();
    }*/
    }//GEN-LAST:event_btnEnServicioActionPerformed

    private void btnDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibleActionPerformed
    /*
        int filaSeleccionada = tblMesas.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa en la tabla.");
        return;
    }
    
    int numMesa = Integer.parseInt(tblMesas.getValueAt(filaSeleccionada, 3).toString());
    
    EntityManager em = conexion.Conexion.crearConexion();
    try {
        em.getTransaction().begin();
        int updated = em.createQuery("UPDATE Mesa m SET m.EstadoMesa = :nuevoEstado WHERE m.numeroMesa = :numMesa")
                        .setParameter("nuevoEstado", 1)
                        .setParameter("numMesa", numMesa)
                        .executeUpdate();
        em.getTransaction().commit();
        
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "La mesa " + numMesa + " se ha marcado como 'Disponible'.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la mesa con número: " + numMesa);
        }
        cargarTabla();
    } catch (Exception e) {
        if (em.getTransaction().isActive()) {
            em.getTransaction().rollback();
        }
        JOptionPane.showMessageDialog(this, "Error al actualizar la mesa: " + e.getMessage());
        e.printStackTrace();
    } finally {
        em.close();
    }
    */
    }//GEN-LAST:event_btnDisponibleActionPerformed

    private void numeroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroMesaActionPerformed

    private void CapacidadMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadMesaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    Coordinador.CoordinadorPantallas.getInstance().mostrarMenu();
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCambiarCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCapacidadActionPerformed
    /*    int filaSeleccionada = tblMesas.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa en la tabla.");
        return;
    }
    
    try {
        int numMesa = Integer.parseInt(numeroMesa.getText().trim());
        int nuevaCapacidad = Integer.parseInt(CapacidadMesa.getText().trim());

        EntityManager em = conexion.Conexion.crearConexion();
        em.getTransaction().begin();
        
        // Ejecutamos la consulta para actualizar la capacidad de la mesa en la base de datos
        int updated = em.createQuery("UPDATE Mesa m SET m.capacidadMesa = :nuevaCap WHERE m.numeroMesa = :numMesa")
                        .setParameter("nuevaCap", nuevaCapacidad)
                        .setParameter("numMesa", numMesa)
                        .executeUpdate();
        
        em.getTransaction().commit();
        em.close();
        
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Capacidad de la mesa " + numMesa + " actualizada a " + nuevaCapacidad + ".");
            cargarTabla(); // Refrescar la tabla para ver el cambio
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la mesa con número " + numMesa + ".");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar la capacidad: " + e.getMessage());
        e.printStackTrace();
    }*/
    }//GEN-LAST:event_btnCambiarCapacidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CapacidadMesa;
    private javax.swing.JButton btnCambiarCapacidad;
    private javax.swing.JButton btnDisponible;
    private javax.swing.JButton btnEnServicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeroMesa;
    private javax.swing.JTable tblMesas;
    // End of variables declaration//GEN-END:variables
}
