/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import BO.MesaBO;
import Coordinador.CoordinadorPantallas;
import Interfaces.IMesaBO;
import Persistencia.MesaDAO;
import interfaces.IMesaDAO;
import javax.swing.JOptionPane;
import negocio.exception.NegocioException;

/**
 *
 * @author Gael
 */
public class PantallaMenu extends javax.swing.JFrame {
    private CoordinadorPantallas ca;
    /**
     * Creates new form PantallaInicio
     */
    public PantallaMenu() {
        initComponents();
        this.ca = CoordinadorPantallas.getInstance();
        this.setLocationRelativeTo(null);
        habilitarBotones();
    }
        public void habilitarBotones(){
        String rol = ca.getRolSeleccionado();
        if (rol.equalsIgnoreCase("Mesero")) {
            btnReservar.setEnabled(true);
            btnMapaMesas.setEnabled(true);
            btnCancelarReservacion.setEnabled(true);
            btnGenerarMesas.setEnabled(false);
            btnGestionarMeseros.setEnabled(false);
            btnGestionarReportes.setEnabled(false);
        } else if (rol.equalsIgnoreCase("Administrador")) {
            btnReservar.setEnabled(true);
            btnMapaMesas.setEnabled(true);
            btnCancelarReservacion.setEnabled(true);
            btnGenerarMesas.setEnabled(true);
            btnGestionarMeseros.setEnabled(true);
            btnGestionarReportes.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnMapaMesas = new javax.swing.JButton();
        btnGestionarMeseros = new javax.swing.JButton();
        btnGestionarReportes = new javax.swing.JButton();
        btnCancelarReservacion = new javax.swing.JButton();
        btnGenerarMesas = new javax.swing.JButton();
        btnHistorialReservaciones = new javax.swing.JButton();
        btnAdministrarMesas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Menu");

        btnReservar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnReservar.setText("Registrar reservación");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnMapaMesas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnMapaMesas.setText("Mapa Mesas");
        btnMapaMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaMesasActionPerformed(evt);
            }
        });

        btnGestionarMeseros.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnGestionarMeseros.setText("Gestionar meseros");
        btnGestionarMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMeserosActionPerformed(evt);
            }
        });

        btnGestionarReportes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnGestionarReportes.setText("Generar reportes");
        btnGestionarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarReportesActionPerformed(evt);
            }
        });

        btnCancelarReservacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnCancelarReservacion.setText("Cancelar Reservación");
        btnCancelarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservacionActionPerformed(evt);
            }
        });

        btnGenerarMesas.setText("Insertar Mesas");
        btnGenerarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMesasActionPerformed(evt);
            }
        });

        btnHistorialReservaciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnHistorialReservaciones.setText("Historial Reservaciones");
        btnHistorialReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialReservacionesActionPerformed(evt);
            }
        });

        btnAdministrarMesas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAdministrarMesas.setText("Administrar Mesas");
        btnAdministrarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarMesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarMesas)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelarReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarMeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorialReservaciones)
                    .addComponent(btnMapaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReservar)
                .addGap(18, 18, 18)
                .addComponent(btnMapaMesas)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialReservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdministrarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarMeseros)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarReservacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnGenerarMesas)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarMapaMesas();
        dispose();
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnMapaMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaMesasActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarMapaMesas();
        dispose();
    }//GEN-LAST:event_btnMapaMesasActionPerformed

    private void btnGestionarMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMeserosActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarGestionMeseros();
        dispose();
    }//GEN-LAST:event_btnGestionarMeserosActionPerformed

    private void btnGestionarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarReportesActionPerformed
        // TODO add your handling code here:
        CoordinadorPantallas.getInstance().mostrarMenuReportes();
        dispose();
    }//GEN-LAST:event_btnGestionarReportesActionPerformed

    private void btnCancelarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservacionActionPerformed
          Coordinador.CoordinadorPantallas.getInstance()
        .mostrarCancelarReservacion();
    }//GEN-LAST:event_btnCancelarReservacionActionPerformed

    private void btnGenerarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMesasActionPerformed
        // TODO add your handling code here:
         try {
        
        IMesaBO mesaBO = new MesaBO();
        int mesasGeneradas = mesaBO.generarMesasIniciales();
        JOptionPane.showMessageDialog(this, mesasGeneradas + " mesas generadas con éxito.");
    } catch (NegocioException e) {
        JOptionPane.showMessageDialog(this, "Error al generar mesas: " + e.getMessage());
    }

    }//GEN-LAST:event_btnGenerarMesasActionPerformed

    private void btnHistorialReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialReservacionesActionPerformed
        Coordinador.CoordinadorPantallas.getInstance().mostrarHistorialReservaciones();
        this.dispose();
    }//GEN-LAST:event_btnHistorialReservacionesActionPerformed

    private void btnAdministrarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarMesasActionPerformed
        Coordinador.CoordinadorPantallas.getInstance().mostrarAdministrarMesas();
        this.dispose();
    }//GEN-LAST:event_btnAdministrarMesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenu().setVisible(true);
                new PantallaMenu().setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarMesas;
    private javax.swing.JButton btnCancelarReservacion;
    private javax.swing.JButton btnGenerarMesas;
    private javax.swing.JButton btnGestionarMeseros;
    private javax.swing.JButton btnGestionarReportes;
    private javax.swing.JButton btnHistorialReservaciones;
    private javax.swing.JButton btnMapaMesas;
    private javax.swing.JButton btnReservar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
