/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Roles;

import Coordinador.CoordinadorPantallas;



/**
 *
 * @author Gael
 */
public class MenuRolesRestaurante extends javax.swing.JFrame {

    private Coordinador.CoordinadorPantallas ca;
    
    /**
     * Creates new form MenuRoles
     */
    public MenuRolesRestaurante() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ca = CoordinadorPantallas.getInstance();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMesero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Roles");

        botonMesero.setBackground(new java.awt.Color(27, 61, 174));
        botonMesero.setForeground(new java.awt.Color(255, 255, 255));
        botonMesero.setText("Mesero");
        botonMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMeseroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Seleccione su rol");

        botonAdministrador.setBackground(new java.awt.Color(27, 61, 174));
        botonAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        botonAdministrador.setText("Administrador");
        botonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonMesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(botonAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(botonMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMeseroActionPerformed
        menuMesero();
    }//GEN-LAST:event_botonMeseroActionPerformed

    private void botonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministradorActionPerformed
        menuAdministrador();
    }//GEN-LAST:event_botonAdministradorActionPerformed

    public void menuMesero(){
        this.dispose();
        ca.setRolSeleccionado("Mesero");
        ca.mostrarMenu();
    }
    
    public void menuAdministrador(){
        this.dispose();
        ca.setRolSeleccionado("Administrador");
        ca.mostrarMenu();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonMesero;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
