/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import BO.MeseroBO;
import Interfaces.IMeseroBO;
import Persistencia.MeseroDAO;
import dtos.MeseroDTO;
import interfaces.IMeseroDAO;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import negocio.exception.NegocioException;

/**
 *
 * @author Gael
 */
public class PantallaDeshabilitarHabilitarMesero extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAgregarMesero
     */
    private List<MeseroDTO> listaMeseros;
    public PantallaDeshabilitarHabilitarMesero() {
        initComponents();
        cargarMeseros();
    }
    private void cargarMeseros() {
    try {
        IMeseroDAO meseroDAO = MeseroDAO.getInstanceDAO();
        IMeseroBO meseroBO = new MeseroBO(meseroDAO);
        listaMeseros = meseroBO.obtenerTodos();  

        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (MeseroDTO mesero : listaMeseros) {
            modelo.addElement(mesero.getNombreConEstado());
        }
        listaMeserosJList.setModel(modelo);

    } catch (NegocioException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar meseros: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRegistrar = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnHabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMeserosJList = new javax.swing.JList<>();
        btnDeshabilitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelRegistrar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        labelRegistrar.setText("Habilitar/Deshabilitar meseros");

        labelNombre.setText("Meseros:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnHabilitar.setText("Habilitar mesero");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaMeserosJList);

        btnDeshabilitar.setText("Deshabilitar mesero");
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnDeshabilitar)
                        .addGap(41, 41, 41)
                        .addComponent(btnHabilitar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labelRegistrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnHabilitar)
                    .addComponent(btnDeshabilitar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Coordinador.CoordinadorPantallas.getInstance().mostrarGestionMeseros();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        // TODO add your handling code here:
            int index = listaMeserosJList.getSelectedIndex();
            if (index < 0) {
                JOptionPane.showMessageDialog(this, "Selecciona un mesero.");
            return;
    }

            MeseroDTO meseroSeleccionado = listaMeseros.get(index);
            if (meseroSeleccionado.isEstado()) {
                JOptionPane.showMessageDialog(this, "El mesero ya está activo.");
            return;
    }

        try {
            IMeseroDAO meseroDAO = MeseroDAO.getInstanceDAO();
            IMeseroBO meseroBO = new MeseroBO(meseroDAO);
            boolean resultado = meseroBO.activarMesero(meseroSeleccionado.getId());

        if (resultado) {
            JOptionPane.showMessageDialog(this, "Mesero habilitado correctamente.");
            cargarMeseros(); 
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo habilitar al mesero.");
        }
         } catch (NegocioException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnHabilitarActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        // TODO add your handling code here:
         int index = listaMeserosJList.getSelectedIndex();
           if (index < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un mesero.");
            return;
    }

        MeseroDTO meseroSeleccionado = listaMeseros.get(index);
            if (!meseroSeleccionado.isEstado()) {
             JOptionPane.showMessageDialog(this, "El mesero ya está inactivo.");
             return;
    }

        try {
            IMeseroDAO meseroDAO = MeseroDAO.getInstanceDAO();
            IMeseroBO meseroBO = new MeseroBO(meseroDAO);
            boolean result = meseroBO.deshabilitarMesero(meseroSeleccionado.getId());

        if (result) {
            JOptionPane.showMessageDialog(this, "Mesero deshabilitado.");
            cargarMeseros();  
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo deshabilitar.");
        }

    } catch (NegocioException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDeshabilitarHabilitarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDeshabilitarHabilitarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDeshabilitarHabilitarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDeshabilitarHabilitarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaDeshabilitarHabilitarMesero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRegistrar;
    private javax.swing.JList<String> listaMeserosJList;
    // End of variables declaration//GEN-END:variables
}
